### PR TITLE
Roland sipos/xstats

### LINKED ISSUE #33: Operational monitoring for DPDK
Define metrics for opmon for data transmission and integrity errors for RX and TX sides on every port.
Corresponding Grafana dashboards need to be defined and added.

### PR DESCRIPTION
**Pull request by roland-sipos**

### CODE REVIEW

**Comment by roland-sipos** [comment]
Tested with HW.

**Review by alessandrothea — APPROVED** [review]
Tested at NP04. The code works, some counter don't make much sense but understanding them can come after the merge.

**Comment by alessandrothea** [comment]
I suggest to remove the commented code before merging

**Comment by roland-sipos** [comment]
Thanks Alessandro

**Pull request merged**
